let leagues = [
    'grand master', 
    'master 1', 
    'diamond 1', 
    'diamond 2', 
    'diamond 3',
    'diamond 4', 
    'diamond 5', 
    'diamond 6',
    'diamond 7',
    'platinum 1', 
    'platinum 2', 
    'platinum 3',
    'platinum 4', 
    'platinum 5', 
    'platinum 6',
    'platinum 7',
    'gold 1', 
    'gold 2', 
    'gold 3',
    'gold 4', 
    'gold 5', 
    'gold 6',
    'gold 7',
    'silver 1', 
    'silver 2', 
    'silver 3',
    'silver 4', 
    'silver 5', 
    'silver 6',
    'silver 7',
    'bronze 1', 
    'bronze 2', 
    'bronze 3',
    'bronze 4', 
    'bronze 5', 
    'bronze 6',
    'bronze 7'
]

module.exports = leagues;